# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supn_remnawave_panel.models.debug_srr_matcher_response_dto import DebugSrrMatcherResponseDto

class TestDebugSrrMatcherResponseDto(unittest.TestCase):
    """DebugSrrMatcherResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DebugSrrMatcherResponseDto:
        """Test DebugSrrMatcherResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DebugSrrMatcherResponseDto`
        """
        model = DebugSrrMatcherResponseDto()
        if include_optional:
            return DebugSrrMatcherResponseDto(
                response = supn_remnawave_panel.models.debug_srr_matcher_response_dto_response.DebugSrrMatcherResponseDto_response(
                    matched = True, 
                    response_type = 'XRAY_JSON', 
                    matched_rule = supn_remnawave_panel.models.debug_srr_matcher_response_dto_response_matched_rule.DebugSrrMatcherResponseDto_response_matchedRule(
                        name = '0', 
                        description = '0', 
                        enabled = True, 
                        operator = 'AND', 
                        conditions = [
                            supn_remnawave_panel.models.debug_srr_matcher_request_dto_response_rules_rules_inner_conditions_inner.DebugSrrMatcherRequestDto_responseRules_rules_inner_conditions_inner(
                                header_name = 'E', 
                                operator = 'EQUALS', 
                                value = '0', 
                                case_sensitive = True, )
                            ], 
                        response_type = 'XRAY_JSON', 
                        response_modifications = supn_remnawave_panel.models.debug_srr_matcher_request_dto_response_rules_rules_inner_response_modifications.DebugSrrMatcherRequestDto_responseRules_rules_inner_responseModifications(
                            headers = [
                                supn_remnawave_panel.models.debug_srr_matcher_request_dto_response_rules_rules_inner_response_modifications_headers_inner.DebugSrrMatcherRequestDto_responseRules_rules_inner_responseModifications_headers_inner(
                                    key = 'E', 
                                    value = '0', )
                                ], 
                            apply_headers_to_end = True, 
                            subscription_template = '0', 
                            ignore_host_xray_json_template = True, 
                            ignore_serve_json_at_base_subscription = True, 
                            additional_extended_clients_regex = [
                                '0'
                                ], ), ), 
                    input_headers = {
                        'key' : ''
                        }, 
                    output_headers = {
                        'key' : ''
                        }, )
            )
        else:
            return DebugSrrMatcherResponseDto(
                response = supn_remnawave_panel.models.debug_srr_matcher_response_dto_response.DebugSrrMatcherResponseDto_response(
                    matched = True, 
                    response_type = 'XRAY_JSON', 
                    matched_rule = supn_remnawave_panel.models.debug_srr_matcher_response_dto_response_matched_rule.DebugSrrMatcherResponseDto_response_matchedRule(
                        name = '0', 
                        description = '0', 
                        enabled = True, 
                        operator = 'AND', 
                        conditions = [
                            supn_remnawave_panel.models.debug_srr_matcher_request_dto_response_rules_rules_inner_conditions_inner.DebugSrrMatcherRequestDto_responseRules_rules_inner_conditions_inner(
                                header_name = 'E', 
                                operator = 'EQUALS', 
                                value = '0', 
                                case_sensitive = True, )
                            ], 
                        response_type = 'XRAY_JSON', 
                        response_modifications = supn_remnawave_panel.models.debug_srr_matcher_request_dto_response_rules_rules_inner_response_modifications.DebugSrrMatcherRequestDto_responseRules_rules_inner_responseModifications(
                            headers = [
                                supn_remnawave_panel.models.debug_srr_matcher_request_dto_response_rules_rules_inner_response_modifications_headers_inner.DebugSrrMatcherRequestDto_responseRules_rules_inner_responseModifications_headers_inner(
                                    key = 'E', 
                                    value = '0', )
                                ], 
                            apply_headers_to_end = True, 
                            subscription_template = '0', 
                            ignore_host_xray_json_template = True, 
                            ignore_serve_json_at_base_subscription = True, 
                            additional_extended_clients_regex = [
                                '0'
                                ], ), ), 
                    input_headers = {
                        'key' : ''
                        }, 
                    output_headers = {
                        'key' : ''
                        }, ),
        )
        """

    def testDebugSrrMatcherResponseDto(self):
        """Test DebugSrrMatcherResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
