# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supn_remnawave_panel.models.get_infra_providers_response_dto import GetInfraProvidersResponseDto

class TestGetInfraProvidersResponseDto(unittest.TestCase):
    """GetInfraProvidersResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetInfraProvidersResponseDto:
        """Test GetInfraProvidersResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetInfraProvidersResponseDto`
        """
        model = GetInfraProvidersResponseDto()
        if include_optional:
            return GetInfraProvidersResponseDto(
                response = supn_remnawave_panel.models.get_infra_providers_response_dto_response.GetInfraProvidersResponseDto_response(
                    total = 1.337, 
                    providers = [
                        supn_remnawave_panel.models.get_infra_providers_response_dto_response_providers_inner.GetInfraProvidersResponseDto_response_providers_inner(
                            uuid = '', 
                            name = '', 
                            favicon_link = '', 
                            login_url = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            billing_history = supn_remnawave_panel.models.get_infra_providers_response_dto_response_providers_inner_billing_history.GetInfraProvidersResponseDto_response_providers_inner_billingHistory(
                                total_amount = 1.337, 
                                total_bills = 1.337, ), 
                            billing_nodes = [
                                supn_remnawave_panel.models.get_infra_providers_response_dto_response_providers_inner_billing_nodes_inner.GetInfraProvidersResponseDto_response_providers_inner_billingNodes_inner(
                                    node_uuid = '', 
                                    name = '', 
                                    country_code = '', )
                                ], )
                        ], )
            )
        else:
            return GetInfraProvidersResponseDto(
                response = supn_remnawave_panel.models.get_infra_providers_response_dto_response.GetInfraProvidersResponseDto_response(
                    total = 1.337, 
                    providers = [
                        supn_remnawave_panel.models.get_infra_providers_response_dto_response_providers_inner.GetInfraProvidersResponseDto_response_providers_inner(
                            uuid = '', 
                            name = '', 
                            favicon_link = '', 
                            login_url = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            billing_history = supn_remnawave_panel.models.get_infra_providers_response_dto_response_providers_inner_billing_history.GetInfraProvidersResponseDto_response_providers_inner_billingHistory(
                                total_amount = 1.337, 
                                total_bills = 1.337, ), 
                            billing_nodes = [
                                supn_remnawave_panel.models.get_infra_providers_response_dto_response_providers_inner_billing_nodes_inner.GetInfraProvidersResponseDto_response_providers_inner_billingNodes_inner(
                                    node_uuid = '', 
                                    name = '', 
                                    country_code = '', )
                                ], )
                        ], ),
        )
        """

    def testGetInfraProvidersResponseDto(self):
        """Test GetInfraProvidersResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
