# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supn_remnawave_panel.api.config_profiles_controller_api import ConfigProfilesControllerApi


class TestConfigProfilesControllerApi(unittest.IsolatedAsyncioTestCase):
    """ConfigProfilesControllerApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ConfigProfilesControllerApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_config_profile_controller_create_config_profile(self) -> None:
        """Test case for config_profile_controller_create_config_profile

        Create config profile
        """
        pass

    async def test_config_profile_controller_delete_config_profile_by_uuid(self) -> None:
        """Test case for config_profile_controller_delete_config_profile_by_uuid

        Delete config profile
        """
        pass

    async def test_config_profile_controller_get_all_inbounds(self) -> None:
        """Test case for config_profile_controller_get_all_inbounds

        Get all inbounds from all config profiles
        """
        pass

    async def test_config_profile_controller_get_computed_config_profile_by_uuid(self) -> None:
        """Test case for config_profile_controller_get_computed_config_profile_by_uuid

        Get computed config profile by uuid
        """
        pass

    async def test_config_profile_controller_get_config_profile_by_uuid(self) -> None:
        """Test case for config_profile_controller_get_config_profile_by_uuid

        Get config profile by uuid
        """
        pass

    async def test_config_profile_controller_get_config_profiles(self) -> None:
        """Test case for config_profile_controller_get_config_profiles

        Get config profiles
        """
        pass

    async def test_config_profile_controller_get_inbounds_by_profile_uuid(self) -> None:
        """Test case for config_profile_controller_get_inbounds_by_profile_uuid

        Get inbounds by profile uuid
        """
        pass

    async def test_config_profile_controller_reorder_config_profiles(self) -> None:
        """Test case for config_profile_controller_reorder_config_profiles

        Reorder config profiles
        """
        pass

    async def test_config_profile_controller_update_config_profile(self) -> None:
        """Test case for config_profile_controller_update_config_profile

        Update Core Config in specific config profile
        """
        pass


if __name__ == '__main__':
    unittest.main()
