# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supn_remnawave_panel.api.users_bulk_actions_controller_api import UsersBulkActionsControllerApi


class TestUsersBulkActionsControllerApi(unittest.IsolatedAsyncioTestCase):
    """UsersBulkActionsControllerApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = UsersBulkActionsControllerApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_users_bulk_actions_controller_bulk_all_extend_expiration_date(self) -> None:
        """Test case for users_bulk_actions_controller_bulk_all_extend_expiration_date

        Bulk Extend All Users Expiration Date
        """
        pass

    async def test_users_bulk_actions_controller_bulk_all_reset_user_traffic(self) -> None:
        """Test case for users_bulk_actions_controller_bulk_all_reset_user_traffic

        Bulk Reset All Users Traffic
        """
        pass

    async def test_users_bulk_actions_controller_bulk_delete_users(self) -> None:
        """Test case for users_bulk_actions_controller_bulk_delete_users

        Bulk delete users by UUIDs
        """
        pass

    async def test_users_bulk_actions_controller_bulk_delete_users_by_status(self) -> None:
        """Test case for users_bulk_actions_controller_bulk_delete_users_by_status

        Bulk delete users by status
        """
        pass

    async def test_users_bulk_actions_controller_bulk_extend_expiration_date(self) -> None:
        """Test case for users_bulk_actions_controller_bulk_extend_expiration_date

        Bulk Extend Users Expiration Date
        """
        pass

    async def test_users_bulk_actions_controller_bulk_reset_user_traffic(self) -> None:
        """Test case for users_bulk_actions_controller_bulk_reset_user_traffic

        Bulk reset traffic users by UUIDs
        """
        pass

    async def test_users_bulk_actions_controller_bulk_revoke_users_subscription(self) -> None:
        """Test case for users_bulk_actions_controller_bulk_revoke_users_subscription

        Revoke users subscription by User UUIDs
        """
        pass

    async def test_users_bulk_actions_controller_bulk_update_all_users(self) -> None:
        """Test case for users_bulk_actions_controller_bulk_update_all_users

        Bulk update all users
        """
        pass

    async def test_users_bulk_actions_controller_bulk_update_users(self) -> None:
        """Test case for users_bulk_actions_controller_bulk_update_users

        Bulk update users by UUIDs
        """
        pass

    async def test_users_bulk_actions_controller_bulk_update_users_internal_squads(self) -> None:
        """Test case for users_bulk_actions_controller_bulk_update_users_internal_squads

        Bulk update users internal squads by UUIDs
        """
        pass


if __name__ == '__main__':
    unittest.main()
