# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supn_remnawave_panel.models.get_raw_subscription_by_short_uuid_response_dto import GetRawSubscriptionByShortUuidResponseDto

class TestGetRawSubscriptionByShortUuidResponseDto(unittest.TestCase):
    """GetRawSubscriptionByShortUuidResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRawSubscriptionByShortUuidResponseDto:
        """Test GetRawSubscriptionByShortUuidResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRawSubscriptionByShortUuidResponseDto`
        """
        model = GetRawSubscriptionByShortUuidResponseDto()
        if include_optional:
            return GetRawSubscriptionByShortUuidResponseDto(
                response = supn_remnawave_panel.models.get_raw_subscription_by_short_uuid_response_dto_response.GetRawSubscriptionByShortUuidResponseDto_response(
                    user = supn_remnawave_panel.models.create_user_response_dto_response.CreateUserResponseDto_response(
                        uuid = '', 
                        id = 1.337, 
                        short_uuid = '', 
                        username = '', 
                        status = 'ACTIVE', 
                        traffic_limit_bytes = 56, 
                        traffic_limit_strategy = 'NO_RESET', 
                        expire_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        telegram_id = 56, 
                        email = '', 
                        description = '', 
                        tag = '', 
                        hwid_device_limit = 56, 
                        external_squad_uuid = '', 
                        trojan_password = '', 
                        vless_uuid = '', 
                        ss_password = '', 
                        last_triggered_threshold = 56, 
                        sub_revoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_traffic_reset_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        subscription_url = '', 
                        active_internal_squads = [
                            supn_remnawave_panel.models.create_user_response_dto_response_active_internal_squads_inner.CreateUserResponseDto_response_activeInternalSquads_inner(
                                uuid = '', 
                                name = '', )
                            ], 
                        user_traffic = supn_remnawave_panel.models.create_user_response_dto_response_user_traffic.CreateUserResponseDto_response_userTraffic(
                            used_traffic_bytes = 1.337, 
                            lifetime_used_traffic_bytes = 1.337, 
                            online_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            first_connected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            last_connected_node_uuid = '', ), ), 
                    converted_user_info = supn_remnawave_panel.models.get_raw_subscription_by_short_uuid_response_dto_response_converted_user_info.GetRawSubscriptionByShortUuidResponseDto_response_convertedUserInfo(
                        days_left = 1.337, 
                        traffic_limit = '', 
                        traffic_used = '', 
                        lifetime_traffic_used = '', 
                        is_hwid_limited = True, ), 
                    headers = {
                        'key' : ''
                        }, 
                    resolved_proxy_configs = [
                        supn_remnawave_panel.models.get_raw_subscription_by_short_uuid_response_dto_response_resolved_proxy_configs_inner.GetRawSubscriptionByShortUuidResponseDto_response_resolvedProxyConfigs_inner(
                            final_remark = '', 
                            address = '', 
                            port = 0, 
                            protocol = 'vless', 
                            protocol_options = null, 
                            transport = 'tcp', 
                            transport_options = null, 
                            security = 'tls', 
                            security_options = null, 
                            stream_overrides = supn_remnawave_panel.models.get_raw_subscription_by_short_uuid_response_dto_response_resolved_proxy_configs_inner_stream_overrides.GetRawSubscriptionByShortUuidResponseDto_response_resolvedProxyConfigs_inner_streamOverrides(
                                final_mask = null, 
                                sockopt = null, ), 
                            mux = null, 
                            client_overrides = supn_remnawave_panel.models.get_raw_subscription_by_short_uuid_response_dto_response_resolved_proxy_configs_inner_client_overrides.GetRawSubscriptionByShortUuidResponseDto_response_resolvedProxyConfigs_inner_clientOverrides(
                                shuffle_host = True, 
                                mihomo_x25519 = True, 
                                server_description = '', 
                                xray_json_template = null, ), 
                            metadata = supn_remnawave_panel.models.get_raw_subscription_by_short_uuid_response_dto_response_resolved_proxy_configs_inner_metadata.GetRawSubscriptionByShortUuidResponseDto_response_resolvedProxyConfigs_inner_metadata(
                                uuid = '', 
                                tag = '', 
                                exclude_from_subscription_types = [
                                    'XRAY_JSON'
                                    ], 
                                inbound_tag = '', 
                                config_profile_uuid = '', 
                                config_profile_inbound_uuid = '', 
                                is_disabled = True, 
                                is_hidden = True, 
                                view_position = 56, 
                                remark = '', 
                                vless_route_id = 56, 
                                raw_inbound = null, ), )
                        ], )
            )
        else:
            return GetRawSubscriptionByShortUuidResponseDto(
                response = supn_remnawave_panel.models.get_raw_subscription_by_short_uuid_response_dto_response.GetRawSubscriptionByShortUuidResponseDto_response(
                    user = supn_remnawave_panel.models.create_user_response_dto_response.CreateUserResponseDto_response(
                        uuid = '', 
                        id = 1.337, 
                        short_uuid = '', 
                        username = '', 
                        status = 'ACTIVE', 
                        traffic_limit_bytes = 56, 
                        traffic_limit_strategy = 'NO_RESET', 
                        expire_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        telegram_id = 56, 
                        email = '', 
                        description = '', 
                        tag = '', 
                        hwid_device_limit = 56, 
                        external_squad_uuid = '', 
                        trojan_password = '', 
                        vless_uuid = '', 
                        ss_password = '', 
                        last_triggered_threshold = 56, 
                        sub_revoked_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        last_traffic_reset_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        subscription_url = '', 
                        active_internal_squads = [
                            supn_remnawave_panel.models.create_user_response_dto_response_active_internal_squads_inner.CreateUserResponseDto_response_activeInternalSquads_inner(
                                uuid = '', 
                                name = '', )
                            ], 
                        user_traffic = supn_remnawave_panel.models.create_user_response_dto_response_user_traffic.CreateUserResponseDto_response_userTraffic(
                            used_traffic_bytes = 1.337, 
                            lifetime_used_traffic_bytes = 1.337, 
                            online_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            first_connected_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            last_connected_node_uuid = '', ), ), 
                    converted_user_info = supn_remnawave_panel.models.get_raw_subscription_by_short_uuid_response_dto_response_converted_user_info.GetRawSubscriptionByShortUuidResponseDto_response_convertedUserInfo(
                        days_left = 1.337, 
                        traffic_limit = '', 
                        traffic_used = '', 
                        lifetime_traffic_used = '', 
                        is_hwid_limited = True, ), 
                    headers = {
                        'key' : ''
                        }, 
                    resolved_proxy_configs = [
                        supn_remnawave_panel.models.get_raw_subscription_by_short_uuid_response_dto_response_resolved_proxy_configs_inner.GetRawSubscriptionByShortUuidResponseDto_response_resolvedProxyConfigs_inner(
                            final_remark = '', 
                            address = '', 
                            port = 0, 
                            protocol = 'vless', 
                            protocol_options = null, 
                            transport = 'tcp', 
                            transport_options = null, 
                            security = 'tls', 
                            security_options = null, 
                            stream_overrides = supn_remnawave_panel.models.get_raw_subscription_by_short_uuid_response_dto_response_resolved_proxy_configs_inner_stream_overrides.GetRawSubscriptionByShortUuidResponseDto_response_resolvedProxyConfigs_inner_streamOverrides(
                                final_mask = null, 
                                sockopt = null, ), 
                            mux = null, 
                            client_overrides = supn_remnawave_panel.models.get_raw_subscription_by_short_uuid_response_dto_response_resolved_proxy_configs_inner_client_overrides.GetRawSubscriptionByShortUuidResponseDto_response_resolvedProxyConfigs_inner_clientOverrides(
                                shuffle_host = True, 
                                mihomo_x25519 = True, 
                                server_description = '', 
                                xray_json_template = null, ), 
                            metadata = supn_remnawave_panel.models.get_raw_subscription_by_short_uuid_response_dto_response_resolved_proxy_configs_inner_metadata.GetRawSubscriptionByShortUuidResponseDto_response_resolvedProxyConfigs_inner_metadata(
                                uuid = '', 
                                tag = '', 
                                exclude_from_subscription_types = [
                                    'XRAY_JSON'
                                    ], 
                                inbound_tag = '', 
                                config_profile_uuid = '', 
                                config_profile_inbound_uuid = '', 
                                is_disabled = True, 
                                is_hidden = True, 
                                view_position = 56, 
                                remark = '', 
                                vless_route_id = 56, 
                                raw_inbound = null, ), )
                        ], ),
        )
        """

    def testGetRawSubscriptionByShortUuidResponseDto(self):
        """Test GetRawSubscriptionByShortUuidResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
