# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supn_remnawave_panel.models.bulk_disable_hosts_response_dto import BulkDisableHostsResponseDto

class TestBulkDisableHostsResponseDto(unittest.TestCase):
    """BulkDisableHostsResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkDisableHostsResponseDto:
        """Test BulkDisableHostsResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkDisableHostsResponseDto`
        """
        model = BulkDisableHostsResponseDto()
        if include_optional:
            return BulkDisableHostsResponseDto(
                response = [
                    supn_remnawave_panel.models.create_host_response_dto_response.CreateHostResponseDto_response(
                        uuid = '', 
                        view_position = 56, 
                        remark = '', 
                        address = '', 
                        port = 56, 
                        path = '', 
                        sni = '', 
                        host = '', 
                        alpn = '', 
                        fingerprint = '', 
                        is_disabled = True, 
                        security_layer = 'DEFAULT', 
                        x_http_extra_params = null, 
                        mux_params = null, 
                        sockopt_params = null, 
                        final_mask = null, 
                        inbound = supn_remnawave_panel.models.create_host_response_dto_response_inbound.CreateHostResponseDto_response_inbound(
                            config_profile_uuid = '', 
                            config_profile_inbound_uuid = '', ), 
                        server_description = '', 
                        tag = '', 
                        is_hidden = True, 
                        override_sni_from_address = True, 
                        keep_sni_blank = True, 
                        vless_route_id = 0, 
                        allow_insecure = True, 
                        shuffle_host = True, 
                        mihomo_x25519 = True, 
                        nodes = [
                            ''
                            ], 
                        xray_json_template_uuid = '', 
                        excluded_internal_squads = [
                            ''
                            ], 
                        exclude_from_subscription_types = [
                            'XRAY_JSON'
                            ], )
                    ]
            )
        else:
            return BulkDisableHostsResponseDto(
                response = [
                    supn_remnawave_panel.models.create_host_response_dto_response.CreateHostResponseDto_response(
                        uuid = '', 
                        view_position = 56, 
                        remark = '', 
                        address = '', 
                        port = 56, 
                        path = '', 
                        sni = '', 
                        host = '', 
                        alpn = '', 
                        fingerprint = '', 
                        is_disabled = True, 
                        security_layer = 'DEFAULT', 
                        x_http_extra_params = null, 
                        mux_params = null, 
                        sockopt_params = null, 
                        final_mask = null, 
                        inbound = supn_remnawave_panel.models.create_host_response_dto_response_inbound.CreateHostResponseDto_response_inbound(
                            config_profile_uuid = '', 
                            config_profile_inbound_uuid = '', ), 
                        server_description = '', 
                        tag = '', 
                        is_hidden = True, 
                        override_sni_from_address = True, 
                        keep_sni_blank = True, 
                        vless_route_id = 0, 
                        allow_insecure = True, 
                        shuffle_host = True, 
                        mihomo_x25519 = True, 
                        nodes = [
                            ''
                            ], 
                        xray_json_template_uuid = '', 
                        excluded_internal_squads = [
                            ''
                            ], 
                        exclude_from_subscription_types = [
                            'XRAY_JSON'
                            ], )
                    ],
        )
        """

    def testBulkDisableHostsResponseDto(self):
        """Test BulkDisableHostsResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
