# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supn_remnawave_panel.models.get_raw_subscription_by_short_uuid_response_dto_response_resolved_proxy_configs_inner import GetRawSubscriptionByShortUuidResponseDtoResponseResolvedProxyConfigsInner

class TestGetRawSubscriptionByShortUuidResponseDtoResponseResolvedProxyConfigsInner(unittest.TestCase):
    """GetRawSubscriptionByShortUuidResponseDtoResponseResolvedProxyConfigsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRawSubscriptionByShortUuidResponseDtoResponseResolvedProxyConfigsInner:
        """Test GetRawSubscriptionByShortUuidResponseDtoResponseResolvedProxyConfigsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRawSubscriptionByShortUuidResponseDtoResponseResolvedProxyConfigsInner`
        """
        model = GetRawSubscriptionByShortUuidResponseDtoResponseResolvedProxyConfigsInner()
        if include_optional:
            return GetRawSubscriptionByShortUuidResponseDtoResponseResolvedProxyConfigsInner(
                final_remark = '',
                address = '',
                port = 0,
                protocol = 'vless',
                protocol_options = None,
                transport = 'tcp',
                transport_options = None,
                security = 'tls',
                security_options = None,
                stream_overrides = supn_remnawave_panel.models.get_raw_subscription_by_short_uuid_response_dto_response_resolved_proxy_configs_inner_stream_overrides.GetRawSubscriptionByShortUuidResponseDto_response_resolvedProxyConfigs_inner_streamOverrides(
                    final_mask = null, 
                    sockopt = null, ),
                mux = None,
                client_overrides = supn_remnawave_panel.models.get_raw_subscription_by_short_uuid_response_dto_response_resolved_proxy_configs_inner_client_overrides.GetRawSubscriptionByShortUuidResponseDto_response_resolvedProxyConfigs_inner_clientOverrides(
                    shuffle_host = True, 
                    mihomo_x25519 = True, 
                    server_description = '', 
                    xray_json_template = null, ),
                metadata = supn_remnawave_panel.models.get_raw_subscription_by_short_uuid_response_dto_response_resolved_proxy_configs_inner_metadata.GetRawSubscriptionByShortUuidResponseDto_response_resolvedProxyConfigs_inner_metadata(
                    uuid = '', 
                    tag = '', 
                    exclude_from_subscription_types = [
                        'XRAY_JSON'
                        ], 
                    inbound_tag = '', 
                    config_profile_uuid = '', 
                    config_profile_inbound_uuid = '', 
                    is_disabled = True, 
                    is_hidden = True, 
                    view_position = 56, 
                    remark = '', 
                    vless_route_id = 56, 
                    raw_inbound = null, )
            )
        else:
            return GetRawSubscriptionByShortUuidResponseDtoResponseResolvedProxyConfigsInner(
                final_remark = '',
                address = '',
                port = 0,
                protocol = 'vless',
                protocol_options = None,
                transport = 'tcp',
                transport_options = None,
                security = 'tls',
                stream_overrides = supn_remnawave_panel.models.get_raw_subscription_by_short_uuid_response_dto_response_resolved_proxy_configs_inner_stream_overrides.GetRawSubscriptionByShortUuidResponseDto_response_resolvedProxyConfigs_inner_streamOverrides(
                    final_mask = null, 
                    sockopt = null, ),
                mux = None,
                client_overrides = supn_remnawave_panel.models.get_raw_subscription_by_short_uuid_response_dto_response_resolved_proxy_configs_inner_client_overrides.GetRawSubscriptionByShortUuidResponseDto_response_resolvedProxyConfigs_inner_clientOverrides(
                    shuffle_host = True, 
                    mihomo_x25519 = True, 
                    server_description = '', 
                    xray_json_template = null, ),
                metadata = supn_remnawave_panel.models.get_raw_subscription_by_short_uuid_response_dto_response_resolved_proxy_configs_inner_metadata.GetRawSubscriptionByShortUuidResponseDto_response_resolvedProxyConfigs_inner_metadata(
                    uuid = '', 
                    tag = '', 
                    exclude_from_subscription_types = [
                        'XRAY_JSON'
                        ], 
                    inbound_tag = '', 
                    config_profile_uuid = '', 
                    config_profile_inbound_uuid = '', 
                    is_disabled = True, 
                    is_hidden = True, 
                    view_position = 56, 
                    remark = '', 
                    vless_route_id = 56, 
                    raw_inbound = null, ),
        )
        """

    def testGetRawSubscriptionByShortUuidResponseDtoResponseResolvedProxyConfigsInner(self):
        """Test GetRawSubscriptionByShortUuidResponseDtoResponseResolvedProxyConfigsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
