# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supn_remnawave_panel.models.debug_srr_matcher_request_dto_response_rules_rules_inner_conditions_inner import DebugSrrMatcherRequestDtoResponseRulesRulesInnerConditionsInner

class TestDebugSrrMatcherRequestDtoResponseRulesRulesInnerConditionsInner(unittest.TestCase):
    """DebugSrrMatcherRequestDtoResponseRulesRulesInnerConditionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DebugSrrMatcherRequestDtoResponseRulesRulesInnerConditionsInner:
        """Test DebugSrrMatcherRequestDtoResponseRulesRulesInnerConditionsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DebugSrrMatcherRequestDtoResponseRulesRulesInnerConditionsInner`
        """
        model = DebugSrrMatcherRequestDtoResponseRulesRulesInnerConditionsInner()
        if include_optional:
            return DebugSrrMatcherRequestDtoResponseRulesRulesInnerConditionsInner(
                header_name = 'E',
                operator = 'EQUALS',
                value = '0',
                case_sensitive = True
            )
        else:
            return DebugSrrMatcherRequestDtoResponseRulesRulesInnerConditionsInner(
                header_name = 'E',
                operator = 'EQUALS',
                value = '0',
                case_sensitive = True,
        )
        """

    def testDebugSrrMatcherRequestDtoResponseRulesRulesInnerConditionsInner(self):
        """Test DebugSrrMatcherRequestDtoResponseRulesRulesInnerConditionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
