# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supn_remnawave_panel.api.subscription_template_controller_api import SubscriptionTemplateControllerApi


class TestSubscriptionTemplateControllerApi(unittest.IsolatedAsyncioTestCase):
    """SubscriptionTemplateControllerApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SubscriptionTemplateControllerApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_subscription_template_controller_create_template(self) -> None:
        """Test case for subscription_template_controller_create_template

        Create subscription template
        """
        pass

    async def test_subscription_template_controller_delete_template(self) -> None:
        """Test case for subscription_template_controller_delete_template

        Delete subscription template
        """
        pass

    async def test_subscription_template_controller_get_all_templates(self) -> None:
        """Test case for subscription_template_controller_get_all_templates

        Get all subscription templates (wihout content)
        """
        pass

    async def test_subscription_template_controller_get_template_by_uuid(self) -> None:
        """Test case for subscription_template_controller_get_template_by_uuid

        Get subscription template by uuid
        """
        pass

    async def test_subscription_template_controller_reorder_subscription_templates(self) -> None:
        """Test case for subscription_template_controller_reorder_subscription_templates

        Reorder subscription templates
        """
        pass

    async def test_subscription_template_controller_update_template(self) -> None:
        """Test case for subscription_template_controller_update_template

        Update subscription template
        """
        pass


if __name__ == '__main__':
    unittest.main()
