# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supn_remnawave_panel.models.reorder_internal_squads_response_dto import ReorderInternalSquadsResponseDto

class TestReorderInternalSquadsResponseDto(unittest.TestCase):
    """ReorderInternalSquadsResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReorderInternalSquadsResponseDto:
        """Test ReorderInternalSquadsResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReorderInternalSquadsResponseDto`
        """
        model = ReorderInternalSquadsResponseDto()
        if include_optional:
            return ReorderInternalSquadsResponseDto(
                response = supn_remnawave_panel.models.get_internal_squads_response_dto_response.GetInternalSquadsResponseDto_response(
                    total = 1.337, 
                    internal_squads = [
                        supn_remnawave_panel.models.get_internal_squads_response_dto_response_internal_squads_inner.GetInternalSquadsResponseDto_response_internalSquads_inner(
                            uuid = '', 
                            view_position = 56, 
                            name = '', 
                            info = supn_remnawave_panel.models.get_internal_squads_response_dto_response_internal_squads_inner_info.GetInternalSquadsResponseDto_response_internalSquads_inner_info(
                                members_count = 1.337, 
                                inbounds_count = 1.337, ), 
                            inbounds = [
                                supn_remnawave_panel.models.get_config_profiles_response_dto_response_config_profiles_inner_inbounds_inner.GetConfigProfilesResponseDto_response_configProfiles_inner_inbounds_inner(
                                    uuid = '', 
                                    profile_uuid = '', 
                                    tag = '', 
                                    type = '', 
                                    network = '', 
                                    security = '', 
                                    port = 1.337, 
                                    raw_inbound = null, )
                                ], 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], )
            )
        else:
            return ReorderInternalSquadsResponseDto(
                response = supn_remnawave_panel.models.get_internal_squads_response_dto_response.GetInternalSquadsResponseDto_response(
                    total = 1.337, 
                    internal_squads = [
                        supn_remnawave_panel.models.get_internal_squads_response_dto_response_internal_squads_inner.GetInternalSquadsResponseDto_response_internalSquads_inner(
                            uuid = '', 
                            view_position = 56, 
                            name = '', 
                            info = supn_remnawave_panel.models.get_internal_squads_response_dto_response_internal_squads_inner_info.GetInternalSquadsResponseDto_response_internalSquads_inner_info(
                                members_count = 1.337, 
                                inbounds_count = 1.337, ), 
                            inbounds = [
                                supn_remnawave_panel.models.get_config_profiles_response_dto_response_config_profiles_inner_inbounds_inner.GetConfigProfilesResponseDto_response_configProfiles_inner_inbounds_inner(
                                    uuid = '', 
                                    profile_uuid = '', 
                                    tag = '', 
                                    type = '', 
                                    network = '', 
                                    security = '', 
                                    port = 1.337, 
                                    raw_inbound = null, )
                                ], 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], ),
        )
        """

    def testReorderInternalSquadsResponseDto(self):
        """Test ReorderInternalSquadsResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
