# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supn_remnawave_panel.models.delete_passkey_response_dto import DeletePasskeyResponseDto

class TestDeletePasskeyResponseDto(unittest.TestCase):
    """DeletePasskeyResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeletePasskeyResponseDto:
        """Test DeletePasskeyResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeletePasskeyResponseDto`
        """
        model = DeletePasskeyResponseDto()
        if include_optional:
            return DeletePasskeyResponseDto(
                response = supn_remnawave_panel.models.get_all_passkeys_response_dto_response.GetAllPasskeysResponseDto_response(
                    passkeys = [
                        supn_remnawave_panel.models.get_all_passkeys_response_dto_response_passkeys_inner.GetAllPasskeysResponseDto_response_passkeys_inner(
                            id = '', 
                            name = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            last_used_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], )
            )
        else:
            return DeletePasskeyResponseDto(
                response = supn_remnawave_panel.models.get_all_passkeys_response_dto_response.GetAllPasskeysResponseDto_response(
                    passkeys = [
                        supn_remnawave_panel.models.get_all_passkeys_response_dto_response_passkeys_inner.GetAllPasskeysResponseDto_response_passkeys_inner(
                            id = '', 
                            name = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            last_used_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], ),
        )
        """

    def testDeletePasskeyResponseDto(self):
        """Test DeletePasskeyResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
