# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supn_remnawave_panel.models.get_nodes_metrics_response_dto_response_nodes_inner import GetNodesMetricsResponseDtoResponseNodesInner

class TestGetNodesMetricsResponseDtoResponseNodesInner(unittest.TestCase):
    """GetNodesMetricsResponseDtoResponseNodesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetNodesMetricsResponseDtoResponseNodesInner:
        """Test GetNodesMetricsResponseDtoResponseNodesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetNodesMetricsResponseDtoResponseNodesInner`
        """
        model = GetNodesMetricsResponseDtoResponseNodesInner()
        if include_optional:
            return GetNodesMetricsResponseDtoResponseNodesInner(
                node_uuid = '',
                node_name = '',
                country_emoji = '',
                provider_name = '',
                users_online = 1.337,
                inbounds_stats = [
                    supn_remnawave_panel.models.get_nodes_metrics_response_dto_response_nodes_inner_inbounds_stats_inner.GetNodesMetricsResponseDto_response_nodes_inner_inboundsStats_inner(
                        tag = '', 
                        upload = '', 
                        download = '', )
                    ],
                outbounds_stats = [
                    supn_remnawave_panel.models.get_nodes_metrics_response_dto_response_nodes_inner_inbounds_stats_inner.GetNodesMetricsResponseDto_response_nodes_inner_inboundsStats_inner(
                        tag = '', 
                        upload = '', 
                        download = '', )
                    ]
            )
        else:
            return GetNodesMetricsResponseDtoResponseNodesInner(
                node_uuid = '',
                node_name = '',
                country_emoji = '',
                provider_name = '',
                users_online = 1.337,
                inbounds_stats = [
                    supn_remnawave_panel.models.get_nodes_metrics_response_dto_response_nodes_inner_inbounds_stats_inner.GetNodesMetricsResponseDto_response_nodes_inner_inboundsStats_inner(
                        tag = '', 
                        upload = '', 
                        download = '', )
                    ],
                outbounds_stats = [
                    supn_remnawave_panel.models.get_nodes_metrics_response_dto_response_nodes_inner_inbounds_stats_inner.GetNodesMetricsResponseDto_response_nodes_inner_inboundsStats_inner(
                        tag = '', 
                        upload = '', 
                        download = '', )
                    ],
        )
        """

    def testGetNodesMetricsResponseDtoResponseNodesInner(self):
        """Test GetNodesMetricsResponseDtoResponseNodesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
