# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supn_remnawave_panel.api.snippets_controller_api import SnippetsControllerApi


class TestSnippetsControllerApi(unittest.IsolatedAsyncioTestCase):
    """SnippetsControllerApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SnippetsControllerApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_snippets_controller_create_snippet(self) -> None:
        """Test case for snippets_controller_create_snippet

        Create snippet
        """
        pass

    async def test_snippets_controller_delete_snippet_by_name(self) -> None:
        """Test case for snippets_controller_delete_snippet_by_name

        Delete snippet
        """
        pass

    async def test_snippets_controller_get_snippets(self) -> None:
        """Test case for snippets_controller_get_snippets

        Get snippets
        """
        pass

    async def test_snippets_controller_update_snippet(self) -> None:
        """Test case for snippets_controller_update_snippet

        Update snippet
        """
        pass


if __name__ == '__main__':
    unittest.main()
