# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supn_remnawave_panel.models.get_one_node_response_dto import GetOneNodeResponseDto

class TestGetOneNodeResponseDto(unittest.TestCase):
    """GetOneNodeResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOneNodeResponseDto:
        """Test GetOneNodeResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOneNodeResponseDto`
        """
        model = GetOneNodeResponseDto()
        if include_optional:
            return GetOneNodeResponseDto(
                response = supn_remnawave_panel.models.create_node_response_dto_response.CreateNodeResponseDto_response(
                    uuid = '', 
                    name = '', 
                    address = '', 
                    port = 56, 
                    is_connected = True, 
                    is_disabled = True, 
                    is_connecting = True, 
                    last_status_change = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_status_message = '', 
                    is_traffic_tracking_active = True, 
                    traffic_reset_day = 56, 
                    traffic_limit_bytes = 1.337, 
                    traffic_used_bytes = 1.337, 
                    notify_percent = 56, 
                    view_position = 56, 
                    country_code = '', 
                    consumption_multiplier = 1.337, 
                    tags = [
                        ''
                        ], 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    config_profile = supn_remnawave_panel.models.create_node_response_dto_response_config_profile.CreateNodeResponseDto_response_configProfile(
                        active_config_profile_uuid = '', 
                        active_inbounds = [
                            supn_remnawave_panel.models.get_config_profiles_response_dto_response_config_profiles_inner_inbounds_inner.GetConfigProfilesResponseDto_response_configProfiles_inner_inbounds_inner(
                                uuid = '', 
                                profile_uuid = '', 
                                tag = '', 
                                type = '', 
                                network = '', 
                                security = '', 
                                port = 1.337, 
                                raw_inbound = null, )
                            ], ), 
                    provider_uuid = '', 
                    provider = supn_remnawave_panel.models.create_node_response_dto_response_provider.CreateNodeResponseDto_response_provider(
                        uuid = '', 
                        name = '', 
                        favicon_link = '', 
                        login_url = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    active_plugin_uuid = '', 
                    system = supn_remnawave_panel.models.create_node_response_dto_response_system.CreateNodeResponseDto_response_system(
                        info = supn_remnawave_panel.models.create_node_response_dto_response_system_info.CreateNodeResponseDto_response_system_info(
                            arch = '', 
                            cpus = 56, 
                            cpu_model = '', 
                            memory_total = 1.337, 
                            hostname = '', 
                            platform = '', 
                            release = '', 
                            type = '', 
                            version = '', 
                            network_interfaces = [
                                ''
                                ], ), 
                        stats = supn_remnawave_panel.models.create_node_response_dto_response_system_stats.CreateNodeResponseDto_response_system_stats(
                            memory_free = 1.337, 
                            memory_used = 1.337, 
                            uptime = 1.337, 
                            load_avg = [
                                1.337
                                ], 
                            interface = supn_remnawave_panel.models.create_node_response_dto_response_system_stats_interface.CreateNodeResponseDto_response_system_stats_interface(
                                interface = '', 
                                rx_bytes_per_sec = 1.337, 
                                tx_bytes_per_sec = 1.337, 
                                rx_total = 1.337, 
                                tx_total = 1.337, ), ), ), 
                    versions = supn_remnawave_panel.models.create_node_response_dto_response_versions.CreateNodeResponseDto_response_versions(
                        xray = '', 
                        node = '', ), 
                    xray_uptime = 1.337, 
                    users_online = 1.337, )
            )
        else:
            return GetOneNodeResponseDto(
                response = supn_remnawave_panel.models.create_node_response_dto_response.CreateNodeResponseDto_response(
                    uuid = '', 
                    name = '', 
                    address = '', 
                    port = 56, 
                    is_connected = True, 
                    is_disabled = True, 
                    is_connecting = True, 
                    last_status_change = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    last_status_message = '', 
                    is_traffic_tracking_active = True, 
                    traffic_reset_day = 56, 
                    traffic_limit_bytes = 1.337, 
                    traffic_used_bytes = 1.337, 
                    notify_percent = 56, 
                    view_position = 56, 
                    country_code = '', 
                    consumption_multiplier = 1.337, 
                    tags = [
                        ''
                        ], 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    config_profile = supn_remnawave_panel.models.create_node_response_dto_response_config_profile.CreateNodeResponseDto_response_configProfile(
                        active_config_profile_uuid = '', 
                        active_inbounds = [
                            supn_remnawave_panel.models.get_config_profiles_response_dto_response_config_profiles_inner_inbounds_inner.GetConfigProfilesResponseDto_response_configProfiles_inner_inbounds_inner(
                                uuid = '', 
                                profile_uuid = '', 
                                tag = '', 
                                type = '', 
                                network = '', 
                                security = '', 
                                port = 1.337, 
                                raw_inbound = null, )
                            ], ), 
                    provider_uuid = '', 
                    provider = supn_remnawave_panel.models.create_node_response_dto_response_provider.CreateNodeResponseDto_response_provider(
                        uuid = '', 
                        name = '', 
                        favicon_link = '', 
                        login_url = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    active_plugin_uuid = '', 
                    system = supn_remnawave_panel.models.create_node_response_dto_response_system.CreateNodeResponseDto_response_system(
                        info = supn_remnawave_panel.models.create_node_response_dto_response_system_info.CreateNodeResponseDto_response_system_info(
                            arch = '', 
                            cpus = 56, 
                            cpu_model = '', 
                            memory_total = 1.337, 
                            hostname = '', 
                            platform = '', 
                            release = '', 
                            type = '', 
                            version = '', 
                            network_interfaces = [
                                ''
                                ], ), 
                        stats = supn_remnawave_panel.models.create_node_response_dto_response_system_stats.CreateNodeResponseDto_response_system_stats(
                            memory_free = 1.337, 
                            memory_used = 1.337, 
                            uptime = 1.337, 
                            load_avg = [
                                1.337
                                ], 
                            interface = supn_remnawave_panel.models.create_node_response_dto_response_system_stats_interface.CreateNodeResponseDto_response_system_stats_interface(
                                interface = '', 
                                rx_bytes_per_sec = 1.337, 
                                tx_bytes_per_sec = 1.337, 
                                rx_total = 1.337, 
                                tx_total = 1.337, ), ), ), 
                    versions = supn_remnawave_panel.models.create_node_response_dto_response_versions.CreateNodeResponseDto_response_versions(
                        xray = '', 
                        node = '', ), 
                    xray_uptime = 1.337, 
                    users_online = 1.337, ),
        )
        """

    def testGetOneNodeResponseDto(self):
        """Test GetOneNodeResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
