# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supn_remnawave_panel.api.bandwidth_stats_controller_api import BandwidthStatsControllerApi


class TestBandwidthStatsControllerApi(unittest.IsolatedAsyncioTestCase):
    """BandwidthStatsControllerApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = BandwidthStatsControllerApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_bandwidth_stats_nodes_controller_get_node_user_usage(self) -> None:
        """Test case for bandwidth_stats_nodes_controller_get_node_user_usage

        Get Node User Usage by Range and Node UUID (Legacy)
        """
        pass

    async def test_bandwidth_stats_nodes_controller_get_stats_node_users_usage(self) -> None:
        """Test case for bandwidth_stats_nodes_controller_get_stats_node_users_usage

        Get Node Users Usage by Node UUID
        """
        pass

    async def test_bandwidth_stats_users_controller_get_stats_nodes_usage(self) -> None:
        """Test case for bandwidth_stats_users_controller_get_stats_nodes_usage

        Get User Usage by Range
        """
        pass

    async def test_bandwidth_stats_users_controller_get_user_usage_by_range(self) -> None:
        """Test case for bandwidth_stats_users_controller_get_user_usage_by_range

        Get User Usage by Range (Legacy)
        """
        pass

    async def test_nodes_usage_history_controller_get_stats_nodes_usage(self) -> None:
        """Test case for nodes_usage_history_controller_get_stats_nodes_usage

        Get Nodes Usage by Range
        """
        pass


if __name__ == '__main__':
    unittest.main()
