# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supn_remnawave_panel.models.get_stats_response_dto_response import GetStatsResponseDtoResponse

class TestGetStatsResponseDtoResponse(unittest.TestCase):
    """GetStatsResponseDtoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetStatsResponseDtoResponse:
        """Test GetStatsResponseDtoResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetStatsResponseDtoResponse`
        """
        model = GetStatsResponseDtoResponse()
        if include_optional:
            return GetStatsResponseDtoResponse(
                cpu = supn_remnawave_panel.models.get_stats_response_dto_response_cpu.GetStatsResponseDto_response_cpu(
                    cores = 1.337, ),
                memory = supn_remnawave_panel.models.get_stats_response_dto_response_memory.GetStatsResponseDto_response_memory(
                    total = 1.337, 
                    free = 1.337, 
                    used = 1.337, ),
                uptime = 1.337,
                timestamp = 1.337,
                users = supn_remnawave_panel.models.get_stats_response_dto_response_users.GetStatsResponseDto_response_users(
                    status_counts = {
                        'key' : 1.337
                        }, 
                    total_users = 1.337, ),
                online_stats = supn_remnawave_panel.models.get_stats_response_dto_response_online_stats.GetStatsResponseDto_response_onlineStats(
                    last_day = 1.337, 
                    last_week = 1.337, 
                    never_online = 1.337, 
                    online_now = 1.337, ),
                nodes = supn_remnawave_panel.models.get_stats_response_dto_response_nodes.GetStatsResponseDto_response_nodes(
                    total_online = 1.337, 
                    total_bytes_lifetime = '', )
            )
        else:
            return GetStatsResponseDtoResponse(
                cpu = supn_remnawave_panel.models.get_stats_response_dto_response_cpu.GetStatsResponseDto_response_cpu(
                    cores = 1.337, ),
                memory = supn_remnawave_panel.models.get_stats_response_dto_response_memory.GetStatsResponseDto_response_memory(
                    total = 1.337, 
                    free = 1.337, 
                    used = 1.337, ),
                uptime = 1.337,
                timestamp = 1.337,
                users = supn_remnawave_panel.models.get_stats_response_dto_response_users.GetStatsResponseDto_response_users(
                    status_counts = {
                        'key' : 1.337
                        }, 
                    total_users = 1.337, ),
                online_stats = supn_remnawave_panel.models.get_stats_response_dto_response_online_stats.GetStatsResponseDto_response_onlineStats(
                    last_day = 1.337, 
                    last_week = 1.337, 
                    never_online = 1.337, 
                    online_now = 1.337, ),
                nodes = supn_remnawave_panel.models.get_stats_response_dto_response_nodes.GetStatsResponseDto_response_nodes(
                    total_online = 1.337, 
                    total_bytes_lifetime = '', ),
        )
        """

    def testGetStatsResponseDtoResponse(self):
        """Test GetStatsResponseDtoResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
