# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from supn_remnawave_panel.models.create_host_request_dto import CreateHostRequestDto

class TestCreateHostRequestDto(unittest.TestCase):
    """CreateHostRequestDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateHostRequestDto:
        """Test CreateHostRequestDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateHostRequestDto`
        """
        model = CreateHostRequestDto()
        if include_optional:
            return CreateHostRequestDto(
                inbound = supn_remnawave_panel.models.create_host_request_dto_inbound.CreateHostRequestDto_inbound(
                    config_profile_uuid = '', 
                    config_profile_inbound_uuid = '', ),
                remark = '0',
                address = '',
                port = 56,
                path = '',
                sni = '',
                host = '',
                alpn = 'h3',
                fingerprint = 'chrome',
                is_disabled = True,
                security_layer = 'DEFAULT',
                x_http_extra_params = None,
                mux_params = None,
                sockopt_params = None,
                final_mask = None,
                server_description = '',
                tag = 'Z',
                is_hidden = True,
                override_sni_from_address = True,
                keep_sni_blank = True,
                allow_insecure = True,
                vless_route_id = 0,
                shuffle_host = True,
                mihomo_x25519 = True,
                nodes = [
                    ''
                    ],
                xray_json_template_uuid = '',
                excluded_internal_squads = [
                    ''
                    ],
                exclude_from_subscription_types = [
                    'XRAY_JSON'
                    ]
            )
        else:
            return CreateHostRequestDto(
                inbound = supn_remnawave_panel.models.create_host_request_dto_inbound.CreateHostRequestDto_inbound(
                    config_profile_uuid = '', 
                    config_profile_inbound_uuid = '', ),
                remark = '0',
                address = '',
                port = 56,
        )
        """

    def testCreateHostRequestDto(self):
        """Test CreateHostRequestDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
