# Hand-maintained: слой совместимости с remnapy поверх актуального OpenAPI-клиента.
from __future__ import annotations

from supn_remnawave_panel.remnapy_compat.enums import (
    TCRMEvents,
    TErrorsEvents,
    TNodeEvents,
    TResetPeriods,
    TServiceEvents,
    TUserEvents,
    TUserHwidDevicesEvents,
    TUsersStatus,
    TrafficLimitStrategy,
    UserStatus,
)
from supn_remnawave_panel.remnapy_compat.exceptions import (
    ApiError,
    ApiErrorResponse,
    AuthenticationError,
    BadRequestError,
    BusinessLogicError,
    ConflictError,
    FeatureNotAvailableError,
    ForbiddenError,
    MaintenanceError,
    NetworkError,
    NotFoundError,
    QuotaExceededError,
    RateLimitError,
    ServerError,
    UnauthorizedError,
    ValidationError,
    map_openapi_exception,
)
from supn_remnawave_panel.remnapy_compat.sdk import RemnawaveSDK
from supn_remnawave_panel.remnapy_compat.webhooks import (
    WebhookHeadersDto,
    WebhookPayloadDto,
    WebhookUtility,
)

__all__ = [
    "RemnawaveSDK",
    "WebhookUtility",
    "WebhookHeadersDto",
    "WebhookPayloadDto",
    "ApiError",
    "ApiErrorResponse",
    "AuthenticationError",
    "BadRequestError",
    "BusinessLogicError",
    "ConflictError",
    "FeatureNotAvailableError",
    "ForbiddenError",
    "MaintenanceError",
    "NetworkError",
    "NotFoundError",
    "QuotaExceededError",
    "RateLimitError",
    "ServerError",
    "UnauthorizedError",
    "ValidationError",
    "map_openapi_exception",
    "TrafficLimitStrategy",
    "UserStatus",
    "TNodeEvents",
    "TUserEvents",
    "TServiceEvents",
    "TErrorsEvents",
    "TCRMEvents",
    "TUserHwidDevicesEvents",
    "TResetPeriods",
    "TUsersStatus",
]
