# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from uuid import UUID
from supn_remnawave_panel.models.create_node_request_dto_config_profile import CreateNodeRequestDtoConfigProfile
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateNodeRequestDto(BaseModel):
    """
    CreateNodeRequestDto
    """ # noqa: E501
    name: Annotated[str, Field(min_length=3, strict=True, max_length=30)]
    address: Annotated[str, Field(min_length=2, strict=True)]
    port: Optional[Annotated[int, Field(le=65535, strict=True, ge=1)]] = None
    is_traffic_tracking_active: Optional[StrictBool] = Field(default=False, alias="isTrafficTrackingActive")
    traffic_limit_bytes: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, alias="trafficLimitBytes")
    notify_percent: Optional[Annotated[int, Field(le=100, strict=True, ge=0)]] = Field(default=None, alias="notifyPercent")
    traffic_reset_day: Optional[Annotated[int, Field(le=31, strict=True, ge=1)]] = Field(default=None, alias="trafficResetDay")
    country_code: Optional[Annotated[str, Field(strict=True, max_length=2)]] = Field(default='XX', alias="countryCode")
    consumption_multiplier: Optional[Union[Annotated[float, Field(le=100, strict=True, ge=0)], Annotated[int, Field(le=100, strict=True, ge=0)]]] = Field(default=None, alias="consumptionMultiplier")
    config_profile: CreateNodeRequestDtoConfigProfile = Field(alias="configProfile")
    provider_uuid: Optional[UUID] = Field(default=None, alias="providerUuid")
    tags: Optional[Annotated[List[Annotated[str, Field(strict=True, max_length=36)]], Field(max_length=10)]] = None
    active_plugin_uuid: Optional[UUID] = Field(default=None, alias="activePluginUuid")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["name", "address", "port", "isTrafficTrackingActive", "trafficLimitBytes", "notifyPercent", "trafficResetDay", "countryCode", "consumptionMultiplier", "configProfile", "providerUuid", "tags", "activePluginUuid"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateNodeRequestDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of config_profile
        if self.config_profile:
            _dict['configProfile'] = self.config_profile.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if provider_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.provider_uuid is None and "provider_uuid" in self.model_fields_set:
            _dict['providerUuid'] = None

        # set to None if active_plugin_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.active_plugin_uuid is None and "active_plugin_uuid" in self.model_fields_set:
            _dict['activePluginUuid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateNodeRequestDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "address": obj.get("address"),
            "port": obj.get("port"),
            "isTrafficTrackingActive": obj.get("isTrafficTrackingActive") if obj.get("isTrafficTrackingActive") is not None else False,
            "trafficLimitBytes": obj.get("trafficLimitBytes"),
            "notifyPercent": obj.get("notifyPercent"),
            "trafficResetDay": obj.get("trafficResetDay"),
            "countryCode": obj.get("countryCode") if obj.get("countryCode") is not None else 'XX',
            "consumptionMultiplier": obj.get("consumptionMultiplier"),
            "configProfile": CreateNodeRequestDtoConfigProfile.from_dict(obj["configProfile"]) if obj.get("configProfile") is not None else None,
            "providerUuid": obj.get("providerUuid"),
            "tags": obj.get("tags"),
            "activePluginUuid": obj.get("activePluginUuid")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


