# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateUserRequestDto(BaseModel):
    """
    CreateUserRequestDto
    """ # noqa: E501
    username: Annotated[str, Field(min_length=3, strict=True, max_length=36)] = Field(description="Unique username for the user. Required. Must be 3-36 characters long and contain only letters, numbers, underscores and dashes.")
    status: Optional[StrictStr] = Field(default='ACTIVE', description="Optional. User account status. Defaults to ACTIVE.")
    short_uuid: Optional[StrictStr] = Field(default=None, description="Optional. Short UUID identifier for the user.", alias="shortUuid")
    trojan_password: Optional[Annotated[str, Field(min_length=8, strict=True, max_length=32)]] = Field(default=None, description="Optional. Password for Trojan protocol. Must be 8-32 characters.", alias="trojanPassword")
    vless_uuid: Optional[UUID] = Field(default=None, description="Optional. UUID for VLESS protocol. Must be a valid UUID format.", alias="vlessUuid")
    ss_password: Optional[Annotated[str, Field(min_length=8, strict=True, max_length=32)]] = Field(default=None, description="Optional. Password for Shadowsocks protocol. Must be 8-32 characters.", alias="ssPassword")
    traffic_limit_bytes: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Optional. Traffic limit in bytes. Set to 0 for unlimited traffic.", alias="trafficLimitBytes")
    traffic_limit_strategy: Optional[StrictStr] = Field(default='NO_RESET', description="Available reset periods", alias="trafficLimitStrategy")
    expire_at: datetime = Field(description="Account expiration date. Required. Format: 2025-01-17T15:38:45.065Z", alias="expireAt")
    created_at: Optional[datetime] = Field(default=None, description="Optional. Account creation date. Format: 2025-01-17T15:38:45.065Z", alias="createdAt")
    last_traffic_reset_at: Optional[datetime] = Field(default=None, description="Optional. Date of last traffic reset. Format: 2025-01-17T15:38:45.065Z", alias="lastTrafficResetAt")
    description: Optional[StrictStr] = Field(default=None, description="Optional. Additional notes or description for the user account.")
    tag: Optional[Annotated[str, Field(strict=True, max_length=16)]] = Field(default=None, description="Optional. User tag for categorization. Max 16 characters, uppercase letters, numbers and underscores only.")
    telegram_id: Optional[StrictInt] = Field(default=None, description="Optional. Telegram user ID for notifications. Must be an integer.", alias="telegramId")
    email: Optional[StrictStr] = Field(default=None, description="Optional. User email address. Must be a valid email format.")
    hwid_device_limit: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Optional. Maximum number of hardware devices allowed. Must be a positive integer.", alias="hwidDeviceLimit")
    active_internal_squads: Optional[List[UUID]] = Field(default=None, description="Optional. Array of UUIDs representing enabled internal squads.", alias="activeInternalSquads")
    uuid: Optional[UUID] = Field(default=None, description="Optional. Pass UUID to create user with specific UUID, otherwise it will be generated automatically.")
    external_squad_uuid: Optional[UUID] = Field(default=None, description="Optional. External squad UUID.", alias="externalSquadUuid")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["username", "status", "shortUuid", "trojanPassword", "vlessUuid", "ssPassword", "trafficLimitBytes", "trafficLimitStrategy", "expireAt", "createdAt", "lastTrafficResetAt", "description", "tag", "telegramId", "email", "hwidDeviceLimit", "activeInternalSquads", "uuid", "externalSquadUuid"]

    @field_validator('username')
    def username_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[a-zA-Z0-9_-]+$", value):
            raise ValueError(r"must validate the regular expression /^[a-zA-Z0-9_-]+$/")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ACTIVE', 'DISABLED', 'LIMITED', 'EXPIRED']):
            raise ValueError("must be one of enum values ('ACTIVE', 'DISABLED', 'LIMITED', 'EXPIRED')")
        return value

    @field_validator('traffic_limit_strategy')
    def traffic_limit_strategy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NO_RESET', 'DAY', 'WEEK', 'MONTH', 'MONTH_ROLLING']):
            raise ValueError("must be one of enum values ('NO_RESET', 'DAY', 'WEEK', 'MONTH', 'MONTH_ROLLING')")
        return value

    @field_validator('tag')
    def tag_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z0-9_]+$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateUserRequestDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if tag (nullable) is None
        # and model_fields_set contains the field
        if self.tag is None and "tag" in self.model_fields_set:
            _dict['tag'] = None

        # set to None if telegram_id (nullable) is None
        # and model_fields_set contains the field
        if self.telegram_id is None and "telegram_id" in self.model_fields_set:
            _dict['telegramId'] = None

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if external_squad_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.external_squad_uuid is None and "external_squad_uuid" in self.model_fields_set:
            _dict['externalSquadUuid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateUserRequestDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "username": obj.get("username"),
            "status": obj.get("status") if obj.get("status") is not None else 'ACTIVE',
            "shortUuid": obj.get("shortUuid"),
            "trojanPassword": obj.get("trojanPassword"),
            "vlessUuid": obj.get("vlessUuid"),
            "ssPassword": obj.get("ssPassword"),
            "trafficLimitBytes": obj.get("trafficLimitBytes"),
            "trafficLimitStrategy": obj.get("trafficLimitStrategy") if obj.get("trafficLimitStrategy") is not None else 'NO_RESET',
            "expireAt": obj.get("expireAt"),
            "createdAt": obj.get("createdAt"),
            "lastTrafficResetAt": obj.get("lastTrafficResetAt"),
            "description": obj.get("description"),
            "tag": obj.get("tag"),
            "telegramId": obj.get("telegramId"),
            "email": obj.get("email"),
            "hwidDeviceLimit": obj.get("hwidDeviceLimit"),
            "activeInternalSquads": obj.get("activeInternalSquads"),
            "uuid": obj.get("uuid"),
            "externalSquadUuid": obj.get("externalSquadUuid")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


