# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from supn_remnawave_panel.models.create_user_response_dto_response_active_internal_squads_inner import CreateUserResponseDtoResponseActiveInternalSquadsInner
from supn_remnawave_panel.models.create_user_response_dto_response_user_traffic import CreateUserResponseDtoResponseUserTraffic
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateUserResponseDtoResponse(BaseModel):
    """
    CreateUserResponseDtoResponse
    """ # noqa: E501
    uuid: UUID
    id: Union[StrictFloat, StrictInt]
    short_uuid: StrictStr = Field(alias="shortUuid")
    username: StrictStr
    status: Optional[StrictStr] = 'ACTIVE'
    traffic_limit_bytes: Optional[StrictInt] = Field(default=0, alias="trafficLimitBytes")
    traffic_limit_strategy: Optional[StrictStr] = Field(default='NO_RESET', description="Available reset periods", alias="trafficLimitStrategy")
    expire_at: datetime = Field(alias="expireAt")
    telegram_id: Optional[StrictInt] = Field(alias="telegramId")
    email: Optional[StrictStr]
    description: Optional[StrictStr]
    tag: Optional[StrictStr]
    hwid_device_limit: Optional[StrictInt] = Field(alias="hwidDeviceLimit")
    external_squad_uuid: Optional[UUID] = Field(alias="externalSquadUuid")
    trojan_password: StrictStr = Field(alias="trojanPassword")
    vless_uuid: UUID = Field(alias="vlessUuid")
    ss_password: StrictStr = Field(alias="ssPassword")
    last_triggered_threshold: Optional[StrictInt] = Field(default=0, alias="lastTriggeredThreshold")
    sub_revoked_at: Optional[datetime] = Field(alias="subRevokedAt")
    last_traffic_reset_at: Optional[datetime] = Field(alias="lastTrafficResetAt")
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")
    subscription_url: StrictStr = Field(alias="subscriptionUrl")
    active_internal_squads: List[CreateUserResponseDtoResponseActiveInternalSquadsInner] = Field(alias="activeInternalSquads")
    user_traffic: CreateUserResponseDtoResponseUserTraffic = Field(alias="userTraffic")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["uuid", "id", "shortUuid", "username", "status", "trafficLimitBytes", "trafficLimitStrategy", "expireAt", "telegramId", "email", "description", "tag", "hwidDeviceLimit", "externalSquadUuid", "trojanPassword", "vlessUuid", "ssPassword", "lastTriggeredThreshold", "subRevokedAt", "lastTrafficResetAt", "createdAt", "updatedAt", "subscriptionUrl", "activeInternalSquads", "userTraffic"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['ACTIVE', 'DISABLED', 'LIMITED', 'EXPIRED']):
            raise ValueError("must be one of enum values ('ACTIVE', 'DISABLED', 'LIMITED', 'EXPIRED')")
        return value

    @field_validator('traffic_limit_strategy')
    def traffic_limit_strategy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['NO_RESET', 'DAY', 'WEEK', 'MONTH', 'MONTH_ROLLING']):
            raise ValueError("must be one of enum values ('NO_RESET', 'DAY', 'WEEK', 'MONTH', 'MONTH_ROLLING')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateUserResponseDtoResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in active_internal_squads (list)
        _items = []
        if self.active_internal_squads:
            for _item_active_internal_squads in self.active_internal_squads:
                if _item_active_internal_squads:
                    _items.append(_item_active_internal_squads.to_dict())
            _dict['activeInternalSquads'] = _items
        # override the default output from pydantic by calling `to_dict()` of user_traffic
        if self.user_traffic:
            _dict['userTraffic'] = self.user_traffic.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if telegram_id (nullable) is None
        # and model_fields_set contains the field
        if self.telegram_id is None and "telegram_id" in self.model_fields_set:
            _dict['telegramId'] = None

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if tag (nullable) is None
        # and model_fields_set contains the field
        if self.tag is None and "tag" in self.model_fields_set:
            _dict['tag'] = None

        # set to None if hwid_device_limit (nullable) is None
        # and model_fields_set contains the field
        if self.hwid_device_limit is None and "hwid_device_limit" in self.model_fields_set:
            _dict['hwidDeviceLimit'] = None

        # set to None if external_squad_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.external_squad_uuid is None and "external_squad_uuid" in self.model_fields_set:
            _dict['externalSquadUuid'] = None

        # set to None if sub_revoked_at (nullable) is None
        # and model_fields_set contains the field
        if self.sub_revoked_at is None and "sub_revoked_at" in self.model_fields_set:
            _dict['subRevokedAt'] = None

        # set to None if last_traffic_reset_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_traffic_reset_at is None and "last_traffic_reset_at" in self.model_fields_set:
            _dict['lastTrafficResetAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateUserResponseDtoResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "id": obj.get("id"),
            "shortUuid": obj.get("shortUuid"),
            "username": obj.get("username"),
            "status": obj.get("status") if obj.get("status") is not None else 'ACTIVE',
            "trafficLimitBytes": obj.get("trafficLimitBytes") if obj.get("trafficLimitBytes") is not None else 0,
            "trafficLimitStrategy": obj.get("trafficLimitStrategy") if obj.get("trafficLimitStrategy") is not None else 'NO_RESET',
            "expireAt": obj.get("expireAt"),
            "telegramId": obj.get("telegramId"),
            "email": obj.get("email"),
            "description": obj.get("description"),
            "tag": obj.get("tag"),
            "hwidDeviceLimit": obj.get("hwidDeviceLimit"),
            "externalSquadUuid": obj.get("externalSquadUuid"),
            "trojanPassword": obj.get("trojanPassword"),
            "vlessUuid": obj.get("vlessUuid"),
            "ssPassword": obj.get("ssPassword"),
            "lastTriggeredThreshold": obj.get("lastTriggeredThreshold") if obj.get("lastTriggeredThreshold") is not None else 0,
            "subRevokedAt": obj.get("subRevokedAt"),
            "lastTrafficResetAt": obj.get("lastTrafficResetAt"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "subscriptionUrl": obj.get("subscriptionUrl"),
            "activeInternalSquads": [CreateUserResponseDtoResponseActiveInternalSquadsInner.from_dict(_item) for _item in obj["activeInternalSquads"]] if obj.get("activeInternalSquads") is not None else None,
            "userTraffic": CreateUserResponseDtoResponseUserTraffic.from_dict(obj["userTraffic"]) if obj.get("userTraffic") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


