# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from supn_remnawave_panel.models.debug_srr_matcher_response_dto_response_matched_rule import DebugSrrMatcherResponseDtoResponseMatchedRule
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DebugSrrMatcherResponseDtoResponse(BaseModel):
    """
    DebugSrrMatcherResponseDtoResponse
    """ # noqa: E501
    matched: StrictBool
    response_type: StrictStr = Field(alias="responseType")
    matched_rule: Optional[DebugSrrMatcherResponseDtoResponseMatchedRule] = Field(alias="matchedRule")
    input_headers: Dict[str, StrictStr] = Field(alias="inputHeaders")
    output_headers: Dict[str, StrictStr] = Field(alias="outputHeaders")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["matched", "responseType", "matchedRule", "inputHeaders", "outputHeaders"]

    @field_validator('response_type')
    def response_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['XRAY_JSON', 'XRAY_BASE64', 'MIHOMO', 'STASH', 'CLASH', 'SINGBOX', 'BROWSER', 'BLOCK', 'STATUS_CODE_404', 'STATUS_CODE_451', 'SOCKET_DROP']):
            raise ValueError("must be one of enum values ('XRAY_JSON', 'XRAY_BASE64', 'MIHOMO', 'STASH', 'CLASH', 'SINGBOX', 'BROWSER', 'BLOCK', 'STATUS_CODE_404', 'STATUS_CODE_451', 'SOCKET_DROP')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DebugSrrMatcherResponseDtoResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of matched_rule
        if self.matched_rule:
            _dict['matchedRule'] = self.matched_rule.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if matched_rule (nullable) is None
        # and model_fields_set contains the field
        if self.matched_rule is None and "matched_rule" in self.model_fields_set:
            _dict['matchedRule'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DebugSrrMatcherResponseDtoResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "matched": obj.get("matched"),
            "responseType": obj.get("responseType"),
            "matchedRule": DebugSrrMatcherResponseDtoResponseMatchedRule.from_dict(obj["matchedRule"]) if obj.get("matchedRule") is not None else None,
            "inputHeaders": obj.get("inputHeaders"),
            "outputHeaders": obj.get("outputHeaders")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


