# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DebugSrrMatcherRequestDtoResponseRulesRulesInnerConditionsInner(BaseModel):
    """
    {\"markdownDescription\":\"Condition to check against the **headerName**.\",\"defaultSnippets\":[{\"label\":\"Examples: Check if header contains \\\"text/html\\\"\",\"markdownDescription\":\"Condition to check if **headerName** contains \\\"text/html\\\"\",\"body\":{\"headerName\":\"accept\",\"operator\":\"CONTAINS\",\"value\":\"text/html\",\"caseSensitive\":true}}]}
    """ # noqa: E501
    header_name: Annotated[str, Field(strict=True)] = Field(description="{\"markdownDescription\":\"**Name** of the HTTP header to check. Must comply with RFC 7230.\"}", alias="headerName")
    operator: StrictStr = Field(description="{\"errorMessage\":\"Invalid operator. Please select a valid operator.\",\"markdownDescription\":\"Operator to use for comparing the `headerName` with `value`.\",\"markdownEnumDescriptions\":[\"Performs an exact, comparison between the header value and specified string. `string === value`\",\"Ensures the header value does not exactly match the specified string. `string !== value`\",\"Checks if the header value contains the specified string as a substring. `string.includes()`\",\"Verifies the header value does not contain the specified string as a substring. `!string.includes()`\",\"Validates that the header value begins with the specified string. `string.startsWith()`\",\"Validates that the header value does not begin with the specified string. `!string.startsWith()`\",\"Confirms the header value ends with the specified string. `string.endsWith()`\",\"Confirms the header value does not end with the specified string. `!string.endsWith()`\",\"Evaluates if the header value matches the specified regular expression pattern. `regex.test()`\",\"Evaluates if the header value does not match the specified regular expression pattern. `!regex.test()`\"]}")
    value: Annotated[str, Field(min_length=1, strict=True, max_length=255)] = Field(description="{\"markdownDescription\":\"**Value** to check against the **headerName**.\"}")
    case_sensitive: StrictBool = Field(description="{\"markdownDescription\":\"Whether the value is **case sensitive**. \\n\\n - `true`: the value will be compared as is. \\n\\n - `false`: the value will be lowercased **before** comparison.\"}", alias="caseSensitive")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["headerName", "operator", "value", "caseSensitive"]

    @field_validator('header_name')
    def header_name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[!#$%&\'*+\-.0-9A-Z^_`a-z|~]+$", value):
            raise ValueError(r"must validate the regular expression /^[!#$%&'*+\-.0-9A-Z^_`a-z|~]+$/")
        return value

    @field_validator('operator')
    def operator_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['EQUALS', 'NOT_EQUALS', 'CONTAINS', 'NOT_CONTAINS', 'STARTS_WITH', 'NOT_STARTS_WITH', 'ENDS_WITH', 'NOT_ENDS_WITH', 'REGEX', 'NOT_REGEX']):
            raise ValueError("must be one of enum values ('EQUALS', 'NOT_EQUALS', 'CONTAINS', 'NOT_CONTAINS', 'STARTS_WITH', 'NOT_STARTS_WITH', 'ENDS_WITH', 'NOT_ENDS_WITH', 'REGEX', 'NOT_REGEX')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DebugSrrMatcherRequestDtoResponseRulesRulesInnerConditionsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DebugSrrMatcherRequestDtoResponseRulesRulesInnerConditionsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "headerName": obj.get("headerName"),
            "operator": obj.get("operator"),
            "value": obj.get("value"),
            "caseSensitive": obj.get("caseSensitive")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


