# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from supn_remnawave_panel.models.get_external_squads_response_dto_response_external_squads_inner_custom_remarks import GetExternalSquadsResponseDtoResponseExternalSquadsInnerCustomRemarks
from supn_remnawave_panel.models.get_external_squads_response_dto_response_external_squads_inner_host_overrides import GetExternalSquadsResponseDtoResponseExternalSquadsInnerHostOverrides
from supn_remnawave_panel.models.get_external_squads_response_dto_response_external_squads_inner_hwid_settings import GetExternalSquadsResponseDtoResponseExternalSquadsInnerHwidSettings
from supn_remnawave_panel.models.get_external_squads_response_dto_response_external_squads_inner_info import GetExternalSquadsResponseDtoResponseExternalSquadsInnerInfo
from supn_remnawave_panel.models.get_external_squads_response_dto_response_external_squads_inner_subscription_settings import GetExternalSquadsResponseDtoResponseExternalSquadsInnerSubscriptionSettings
from supn_remnawave_panel.models.get_external_squads_response_dto_response_external_squads_inner_templates_inner import GetExternalSquadsResponseDtoResponseExternalSquadsInnerTemplatesInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetExternalSquadsResponseDtoResponseExternalSquadsInner(BaseModel):
    """
    GetExternalSquadsResponseDtoResponseExternalSquadsInner
    """ # noqa: E501
    uuid: UUID
    view_position: StrictInt = Field(alias="viewPosition")
    name: StrictStr
    info: GetExternalSquadsResponseDtoResponseExternalSquadsInnerInfo
    templates: List[GetExternalSquadsResponseDtoResponseExternalSquadsInnerTemplatesInner]
    subscription_settings: Optional[GetExternalSquadsResponseDtoResponseExternalSquadsInnerSubscriptionSettings] = Field(alias="subscriptionSettings")
    host_overrides: Optional[GetExternalSquadsResponseDtoResponseExternalSquadsInnerHostOverrides] = Field(alias="hostOverrides")
    response_headers: Optional[Dict[str, StrictStr]] = Field(alias="responseHeaders")
    hwid_settings: Optional[GetExternalSquadsResponseDtoResponseExternalSquadsInnerHwidSettings] = Field(alias="hwidSettings")
    custom_remarks: Optional[GetExternalSquadsResponseDtoResponseExternalSquadsInnerCustomRemarks] = Field(alias="customRemarks")
    subpage_config_uuid: Optional[UUID] = Field(alias="subpageConfigUuid")
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["uuid", "viewPosition", "name", "info", "templates", "subscriptionSettings", "hostOverrides", "responseHeaders", "hwidSettings", "customRemarks", "subpageConfigUuid", "createdAt", "updatedAt"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetExternalSquadsResponseDtoResponseExternalSquadsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of info
        if self.info:
            _dict['info'] = self.info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in templates (list)
        _items = []
        if self.templates:
            for _item_templates in self.templates:
                if _item_templates:
                    _items.append(_item_templates.to_dict())
            _dict['templates'] = _items
        # override the default output from pydantic by calling `to_dict()` of subscription_settings
        if self.subscription_settings:
            _dict['subscriptionSettings'] = self.subscription_settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of host_overrides
        if self.host_overrides:
            _dict['hostOverrides'] = self.host_overrides.to_dict()
        # override the default output from pydantic by calling `to_dict()` of hwid_settings
        if self.hwid_settings:
            _dict['hwidSettings'] = self.hwid_settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of custom_remarks
        if self.custom_remarks:
            _dict['customRemarks'] = self.custom_remarks.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if subscription_settings (nullable) is None
        # and model_fields_set contains the field
        if self.subscription_settings is None and "subscription_settings" in self.model_fields_set:
            _dict['subscriptionSettings'] = None

        # set to None if host_overrides (nullable) is None
        # and model_fields_set contains the field
        if self.host_overrides is None and "host_overrides" in self.model_fields_set:
            _dict['hostOverrides'] = None

        # set to None if response_headers (nullable) is None
        # and model_fields_set contains the field
        if self.response_headers is None and "response_headers" in self.model_fields_set:
            _dict['responseHeaders'] = None

        # set to None if hwid_settings (nullable) is None
        # and model_fields_set contains the field
        if self.hwid_settings is None and "hwid_settings" in self.model_fields_set:
            _dict['hwidSettings'] = None

        # set to None if custom_remarks (nullable) is None
        # and model_fields_set contains the field
        if self.custom_remarks is None and "custom_remarks" in self.model_fields_set:
            _dict['customRemarks'] = None

        # set to None if subpage_config_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.subpage_config_uuid is None and "subpage_config_uuid" in self.model_fields_set:
            _dict['subpageConfigUuid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetExternalSquadsResponseDtoResponseExternalSquadsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "viewPosition": obj.get("viewPosition"),
            "name": obj.get("name"),
            "info": GetExternalSquadsResponseDtoResponseExternalSquadsInnerInfo.from_dict(obj["info"]) if obj.get("info") is not None else None,
            "templates": [GetExternalSquadsResponseDtoResponseExternalSquadsInnerTemplatesInner.from_dict(_item) for _item in obj["templates"]] if obj.get("templates") is not None else None,
            "subscriptionSettings": GetExternalSquadsResponseDtoResponseExternalSquadsInnerSubscriptionSettings.from_dict(obj["subscriptionSettings"]) if obj.get("subscriptionSettings") is not None else None,
            "hostOverrides": GetExternalSquadsResponseDtoResponseExternalSquadsInnerHostOverrides.from_dict(obj["hostOverrides"]) if obj.get("hostOverrides") is not None else None,
            "responseHeaders": obj.get("responseHeaders"),
            "hwidSettings": GetExternalSquadsResponseDtoResponseExternalSquadsInnerHwidSettings.from_dict(obj["hwidSettings"]) if obj.get("hwidSettings") is not None else None,
            "customRemarks": GetExternalSquadsResponseDtoResponseExternalSquadsInnerCustomRemarks.from_dict(obj["customRemarks"]) if obj.get("customRemarks") is not None else None,
            "subpageConfigUuid": obj.get("subpageConfigUuid"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


