# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from supn_remnawave_panel.models.get_remnawave_settings_response_dto_response_branding_settings import GetRemnawaveSettingsResponseDtoResponseBrandingSettings
from supn_remnawave_panel.models.get_remnawave_settings_response_dto_response_oauth2_settings import GetRemnawaveSettingsResponseDtoResponseOauth2Settings
from supn_remnawave_panel.models.get_remnawave_settings_response_dto_response_passkey_settings import GetRemnawaveSettingsResponseDtoResponsePasskeySettings
from supn_remnawave_panel.models.get_remnawave_settings_response_dto_response_password_settings import GetRemnawaveSettingsResponseDtoResponsePasswordSettings
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetRemnawaveSettingsResponseDtoResponse(BaseModel):
    """
    GetRemnawaveSettingsResponseDtoResponse
    """ # noqa: E501
    passkey_settings: Optional[GetRemnawaveSettingsResponseDtoResponsePasskeySettings] = Field(alias="passkeySettings")
    oauth2_settings: Optional[GetRemnawaveSettingsResponseDtoResponseOauth2Settings] = Field(alias="oauth2Settings")
    password_settings: Optional[GetRemnawaveSettingsResponseDtoResponsePasswordSettings] = Field(alias="passwordSettings")
    branding_settings: Optional[GetRemnawaveSettingsResponseDtoResponseBrandingSettings] = Field(alias="brandingSettings")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["passkeySettings", "oauth2Settings", "passwordSettings", "brandingSettings"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetRemnawaveSettingsResponseDtoResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of passkey_settings
        if self.passkey_settings:
            _dict['passkeySettings'] = self.passkey_settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of oauth2_settings
        if self.oauth2_settings:
            _dict['oauth2Settings'] = self.oauth2_settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of password_settings
        if self.password_settings:
            _dict['passwordSettings'] = self.password_settings.to_dict()
        # override the default output from pydantic by calling `to_dict()` of branding_settings
        if self.branding_settings:
            _dict['brandingSettings'] = self.branding_settings.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if passkey_settings (nullable) is None
        # and model_fields_set contains the field
        if self.passkey_settings is None and "passkey_settings" in self.model_fields_set:
            _dict['passkeySettings'] = None

        # set to None if oauth2_settings (nullable) is None
        # and model_fields_set contains the field
        if self.oauth2_settings is None and "oauth2_settings" in self.model_fields_set:
            _dict['oauth2Settings'] = None

        # set to None if password_settings (nullable) is None
        # and model_fields_set contains the field
        if self.password_settings is None and "password_settings" in self.model_fields_set:
            _dict['passwordSettings'] = None

        # set to None if branding_settings (nullable) is None
        # and model_fields_set contains the field
        if self.branding_settings is None and "branding_settings" in self.model_fields_set:
            _dict['brandingSettings'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetRemnawaveSettingsResponseDtoResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "passkeySettings": GetRemnawaveSettingsResponseDtoResponsePasskeySettings.from_dict(obj["passkeySettings"]) if obj.get("passkeySettings") is not None else None,
            "oauth2Settings": GetRemnawaveSettingsResponseDtoResponseOauth2Settings.from_dict(obj["oauth2Settings"]) if obj.get("oauth2Settings") is not None else None,
            "passwordSettings": GetRemnawaveSettingsResponseDtoResponsePasswordSettings.from_dict(obj["passwordSettings"]) if obj.get("passwordSettings") is not None else None,
            "brandingSettings": GetRemnawaveSettingsResponseDtoResponseBrandingSettings.from_dict(obj["brandingSettings"]) if obj.get("brandingSettings") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


