# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from supn_remnawave_panel.models.metadata_controller_get_user_metadata404_response_one_of import MetadataControllerGetUserMetadata404ResponseOneOf
from supn_remnawave_panel.models.metadata_controller_get_user_metadata404_response_one_of1 import MetadataControllerGetUserMetadata404ResponseOneOf1
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

METADATACONTROLLERGETUSERMETADATA404RESPONSE_ONE_OF_SCHEMAS = ["MetadataControllerGetUserMetadata404ResponseOneOf", "MetadataControllerGetUserMetadata404ResponseOneOf1"]

class MetadataControllerGetUserMetadata404Response(BaseModel):
    """
    MetadataControllerGetUserMetadata404Response
    """
    # data type: MetadataControllerGetUserMetadata404ResponseOneOf
    oneof_schema_1_validator: Optional[MetadataControllerGetUserMetadata404ResponseOneOf] = None
    # data type: MetadataControllerGetUserMetadata404ResponseOneOf1
    oneof_schema_2_validator: Optional[MetadataControllerGetUserMetadata404ResponseOneOf1] = None
    actual_instance: Optional[Union[MetadataControllerGetUserMetadata404ResponseOneOf, MetadataControllerGetUserMetadata404ResponseOneOf1]] = None
    one_of_schemas: Set[str] = { "MetadataControllerGetUserMetadata404ResponseOneOf", "MetadataControllerGetUserMetadata404ResponseOneOf1" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = MetadataControllerGetUserMetadata404Response.model_construct()
        error_messages = []
        match = 0
        # validate data type: MetadataControllerGetUserMetadata404ResponseOneOf
        if not isinstance(v, MetadataControllerGetUserMetadata404ResponseOneOf):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MetadataControllerGetUserMetadata404ResponseOneOf`")
        else:
            match += 1
        # validate data type: MetadataControllerGetUserMetadata404ResponseOneOf1
        if not isinstance(v, MetadataControllerGetUserMetadata404ResponseOneOf1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MetadataControllerGetUserMetadata404ResponseOneOf1`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in MetadataControllerGetUserMetadata404Response with oneOf schemas: MetadataControllerGetUserMetadata404ResponseOneOf, MetadataControllerGetUserMetadata404ResponseOneOf1. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in MetadataControllerGetUserMetadata404Response with oneOf schemas: MetadataControllerGetUserMetadata404ResponseOneOf, MetadataControllerGetUserMetadata404ResponseOneOf1. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into MetadataControllerGetUserMetadata404ResponseOneOf
        try:
            instance.actual_instance = MetadataControllerGetUserMetadata404ResponseOneOf.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into MetadataControllerGetUserMetadata404ResponseOneOf1
        try:
            instance.actual_instance = MetadataControllerGetUserMetadata404ResponseOneOf1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into MetadataControllerGetUserMetadata404Response with oneOf schemas: MetadataControllerGetUserMetadata404ResponseOneOf, MetadataControllerGetUserMetadata404ResponseOneOf1. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into MetadataControllerGetUserMetadata404Response with oneOf schemas: MetadataControllerGetUserMetadata404ResponseOneOf, MetadataControllerGetUserMetadata404ResponseOneOf1. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], MetadataControllerGetUserMetadata404ResponseOneOf, MetadataControllerGetUserMetadata404ResponseOneOf1]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


