# coding: utf-8

"""
    Remnawave Panel API (Supn snapshot) — v2.7.4

     Remnawave is a powerful proxy managment tool, built on top of Xray-core, with a focus on simplicity and ease of use.  ## Resources * https://t.me/remnawave * https://github.com/remnawave * https://docs.rw  ---  **Snapshot (Supn)**: Copy of the public contract at [cdn.docs.rw](https://cdn.docs.rw/docs/openapi.json). Last synced: `2026-03-30T10:03:22Z`. CDN `ETag`: `\"5f63753aaeceaf03d930ffbc4449e6ec\"`. CDN `Last-Modified`: `Mon, 30 Mar 2026 00:09:24 GMT`. Upstream: [remnawave/panel](https://github.com/remnawave/panel) (AGPL-3.0). Regenerate with `python sync_openapi.py`. 

    The version of the OpenAPI document: 2.7.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from supn_remnawave_panel.models.create_host_request_dto_inbound import CreateHostRequestDtoInbound
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateHostRequestDto(BaseModel):
    """
    UpdateHostRequestDto
    """ # noqa: E501
    uuid: UUID
    inbound: Optional[CreateHostRequestDtoInbound] = None
    remark: Optional[Annotated[str, Field(strict=True, max_length=40)]] = None
    address: Optional[StrictStr] = None
    port: Optional[StrictInt] = None
    path: Optional[StrictStr] = None
    sni: Optional[StrictStr] = None
    host: Optional[StrictStr] = None
    alpn: Optional[StrictStr] = None
    fingerprint: Optional[StrictStr] = None
    is_disabled: Optional[StrictBool] = Field(default=None, alias="isDisabled")
    security_layer: Optional[StrictStr] = Field(default=None, alias="securityLayer")
    x_http_extra_params: Optional[Any] = Field(default=None, alias="xHttpExtraParams")
    mux_params: Optional[Any] = Field(default=None, alias="muxParams")
    sockopt_params: Optional[Any] = Field(default=None, alias="sockoptParams")
    final_mask: Optional[Any] = Field(default=None, alias="finalMask")
    server_description: Optional[Annotated[str, Field(strict=True, max_length=30)]] = Field(default=None, alias="serverDescription")
    tag: Optional[Annotated[str, Field(strict=True, max_length=32)]] = Field(default=None, description="Optional. Host tag for categorization. Max 32 characters, uppercase letters, numbers, underscores and colons are allowed.")
    is_hidden: Optional[StrictBool] = Field(default=None, alias="isHidden")
    override_sni_from_address: Optional[StrictBool] = Field(default=None, alias="overrideSniFromAddress")
    keep_sni_blank: Optional[StrictBool] = Field(default=None, alias="keepSniBlank")
    vless_route_id: Optional[Annotated[int, Field(le=65535, strict=True, ge=0)]] = Field(default=None, alias="vlessRouteId")
    allow_insecure: Optional[StrictBool] = Field(default=None, alias="allowInsecure")
    shuffle_host: Optional[StrictBool] = Field(default=None, alias="shuffleHost")
    mihomo_x25519: Optional[StrictBool] = Field(default=None, alias="mihomoX25519")
    nodes: Optional[List[UUID]] = None
    xray_json_template_uuid: Optional[UUID] = Field(default=None, alias="xrayJsonTemplateUuid")
    excluded_internal_squads: Optional[List[UUID]] = Field(default=None, description="Optional. Internal squads from which the host will be excluded.", alias="excludedInternalSquads")
    exclude_from_subscription_types: Optional[List[StrictStr]] = Field(default=None, description="Optional. Subscription types from which the host will be excluded from.", alias="excludeFromSubscriptionTypes")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["uuid", "inbound", "remark", "address", "port", "path", "sni", "host", "alpn", "fingerprint", "isDisabled", "securityLayer", "xHttpExtraParams", "muxParams", "sockoptParams", "finalMask", "serverDescription", "tag", "isHidden", "overrideSniFromAddress", "keepSniBlank", "vlessRouteId", "allowInsecure", "shuffleHost", "mihomoX25519", "nodes", "xrayJsonTemplateUuid", "excludedInternalSquads", "excludeFromSubscriptionTypes"]

    @field_validator('alpn')
    def alpn_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['h3', 'h2', 'http/1.1', 'h2,http/1.1', 'h3,h2,http/1.1', 'h3,h2']):
            raise ValueError("must be one of enum values ('h3', 'h2', 'http/1.1', 'h2,http/1.1', 'h3,h2,http/1.1', 'h3,h2')")
        return value

    @field_validator('fingerprint')
    def fingerprint_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['chrome', 'firefox', 'safari', 'ios', 'android', 'edge', 'qq', 'random', 'randomized']):
            raise ValueError("must be one of enum values ('chrome', 'firefox', 'safari', 'ios', 'android', 'edge', 'qq', 'random', 'randomized')")
        return value

    @field_validator('security_layer')
    def security_layer_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['DEFAULT', 'TLS', 'NONE']):
            raise ValueError("must be one of enum values ('DEFAULT', 'TLS', 'NONE')")
        return value

    @field_validator('tag')
    def tag_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^[A-Z0-9_:]+$", value):
            raise ValueError(r"must validate the regular expression /^[A-Z0-9_:]+$/")
        return value

    @field_validator('exclude_from_subscription_types')
    def exclude_from_subscription_types_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['XRAY_JSON', 'XRAY_BASE64', 'MIHOMO', 'STASH', 'CLASH', 'SINGBOX']):
                raise ValueError("each list item must be one of ('XRAY_JSON', 'XRAY_BASE64', 'MIHOMO', 'STASH', 'CLASH', 'SINGBOX')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateHostRequestDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of inbound
        if self.inbound:
            _dict['inbound'] = self.inbound.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if alpn (nullable) is None
        # and model_fields_set contains the field
        if self.alpn is None and "alpn" in self.model_fields_set:
            _dict['alpn'] = None

        # set to None if fingerprint (nullable) is None
        # and model_fields_set contains the field
        if self.fingerprint is None and "fingerprint" in self.model_fields_set:
            _dict['fingerprint'] = None

        # set to None if x_http_extra_params (nullable) is None
        # and model_fields_set contains the field
        if self.x_http_extra_params is None and "x_http_extra_params" in self.model_fields_set:
            _dict['xHttpExtraParams'] = None

        # set to None if mux_params (nullable) is None
        # and model_fields_set contains the field
        if self.mux_params is None and "mux_params" in self.model_fields_set:
            _dict['muxParams'] = None

        # set to None if sockopt_params (nullable) is None
        # and model_fields_set contains the field
        if self.sockopt_params is None and "sockopt_params" in self.model_fields_set:
            _dict['sockoptParams'] = None

        # set to None if final_mask (nullable) is None
        # and model_fields_set contains the field
        if self.final_mask is None and "final_mask" in self.model_fields_set:
            _dict['finalMask'] = None

        # set to None if server_description (nullable) is None
        # and model_fields_set contains the field
        if self.server_description is None and "server_description" in self.model_fields_set:
            _dict['serverDescription'] = None

        # set to None if tag (nullable) is None
        # and model_fields_set contains the field
        if self.tag is None and "tag" in self.model_fields_set:
            _dict['tag'] = None

        # set to None if vless_route_id (nullable) is None
        # and model_fields_set contains the field
        if self.vless_route_id is None and "vless_route_id" in self.model_fields_set:
            _dict['vlessRouteId'] = None

        # set to None if xray_json_template_uuid (nullable) is None
        # and model_fields_set contains the field
        if self.xray_json_template_uuid is None and "xray_json_template_uuid" in self.model_fields_set:
            _dict['xrayJsonTemplateUuid'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateHostRequestDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uuid": obj.get("uuid"),
            "inbound": CreateHostRequestDtoInbound.from_dict(obj["inbound"]) if obj.get("inbound") is not None else None,
            "remark": obj.get("remark"),
            "address": obj.get("address"),
            "port": obj.get("port"),
            "path": obj.get("path"),
            "sni": obj.get("sni"),
            "host": obj.get("host"),
            "alpn": obj.get("alpn"),
            "fingerprint": obj.get("fingerprint"),
            "isDisabled": obj.get("isDisabled"),
            "securityLayer": obj.get("securityLayer"),
            "xHttpExtraParams": obj.get("xHttpExtraParams"),
            "muxParams": obj.get("muxParams"),
            "sockoptParams": obj.get("sockoptParams"),
            "finalMask": obj.get("finalMask"),
            "serverDescription": obj.get("serverDescription"),
            "tag": obj.get("tag"),
            "isHidden": obj.get("isHidden"),
            "overrideSniFromAddress": obj.get("overrideSniFromAddress"),
            "keepSniBlank": obj.get("keepSniBlank"),
            "vlessRouteId": obj.get("vlessRouteId"),
            "allowInsecure": obj.get("allowInsecure"),
            "shuffleHost": obj.get("shuffleHost"),
            "mihomoX25519": obj.get("mihomoX25519"),
            "nodes": obj.get("nodes"),
            "xrayJsonTemplateUuid": obj.get("xrayJsonTemplateUuid"),
            "excludedInternalSquads": obj.get("excludedInternalSquads"),
            "excludeFromSubscriptionTypes": obj.get("excludeFromSubscriptionTypes")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


